# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 05:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', timezone_field.fields.TimeZoneField()),
                ('notify_iotank_emergency', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('email_daily', models.PositiveSmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Setting',
                'verbose_name_plural': 'Account Settings',
            },
        ),
        migrations.CreateModel(
            name='ioTank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qrcode', models.ImageField(blank=True, editable=False, null=True, upload_to='qrcode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('m', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Minimum Temperature 1')),
                ('x', models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='Maximum Temperature 1')),
                ('m2', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Minimum Temperature 2')),
                ('x2', models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='Maximum Temperature 2')),
                ('mh', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Minimum Humidity')),
                ('xh', models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='Maximum Humidity')),
                ('night_start', models.TimeField(default='19:00', verbose_name='Nighttime Start')),
                ('night_end', models.TimeField(default='07:00', verbose_name='Nighttime End')),
                ('night_max_light', models.DecimalField(decimal_places=2, default=0.5, max_digits=6, verbose_name='Night Maximum Light')),
                ('day_min_light', models.DecimalField(decimal_places=2, default=5000, max_digits=6, verbose_name='Day Minimum Light')),
                ('u', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], default='F', max_length=1, verbose_name='Temperature Unit')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_owner', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ioTank',
                'verbose_name_plural': 'ioTanks',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=36, verbose_name='Task ID')),
                ('type', models.CharField(choices=[('S', 'SMS'), ('E', 'E-mail')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ('owner',),
            },
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentdt', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('I', 'ioTank Emergency')], max_length=1)),
                ('value', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Waterproof Temp')),
                ('t2', models.PositiveSmallIntegerField(verbose_name='Box Temperature')),
                ('h', models.PositiveSmallIntegerField(verbose_name='Humidity')),
                ('uv', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='UV Index')),
                ('l', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='UV Index')),
                ('timestamp', models.DateTimeField(editable=False)),
                ('bot', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='metrics.ioTank')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
            },
        ),
    ]
